{% set name = "django-structlog" %}
{% set version = "9.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eb19bafa837345c62f294ded315c6a12523e16d29b4ba69d9e6ce57c7b0d2925

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2
    - structlog >=21.4.0
    - asgiref >=3.6.0
    - django-ipware >=6.0.2

test:
  imports:
    - django_structlog
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Structured Logging for Django
  home: https://github.com/jrobichaud/django-structlog
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - rxm7706
