{% set name = "django-structlog" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0ada1ac0fa4e90a499fc9ce22fc164830304e7219cab12d3b5ef9c2f2967ff5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2
    - structlog >=21.4.0
    - asgiref >=3.6.0
    - django-ipware >=6.0.2

test:
  imports:
    - django_structlog
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Structured Logging for Django
  home: https://github.com/jrobichaud/django-structlog
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - rxm7706
